# Generated by Django 2.2.1 on 2019-07-30 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0003_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
