# Generated by Django 2.2.1 on 2019-07-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anexos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anexo', models.TextField()),
                ('Estado', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DatosInformativos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portada', models.TextField()),
                ('biografia', models.TextField()),
                ('misionyvision', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DatosPortafolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_portafolio', models.CharField(max_length=100)),
                ('responsable', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=100)),
                ('docente', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_estudiante', models.TextField()),
                ('ultima_modificacion', models.TextField()),
                ('num_diario', models.TextField()),
                ('periodo', models.TextField()),
                ('tiempo', models.TextField()),
                ('fecha', models.TextField()),
                ('docente', models.TextField()),
                ('tema', models.TextField()),
                ('contenidos', models.TextField()),
                ('objetivo', models.TextField()),
                ('actividades', models.TextField()),
                ('estra_aprendizaje', models.TextField()),
                ('resumen', models.TextField()),
                ('reflexion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Evaluaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluacion', models.TextField()),
                ('Estado', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Examenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examen', models.TextField()),
                ('Estado', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Extraclases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_extraclass', models.TextField()),
                ('url', models.TextField()),
                ('Estado', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InformeFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informe', models.TextField()),
                ('estado', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Intraclases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_intraclass', models.TextField()),
                ('url', models.TextField()),
                ('Estado', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_portafolio', models.IntegerField()),
                ('usuario', models.IntegerField()),
                ('estado', models.CharField(max_length=100)),
                ('num_diario', models.IntegerField()),
                ('fecha', models.DateField()),
                ('mensaje', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PracticaLaboratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practica', models.TextField()),
                ('url', models.TextField()),
                ('Estado', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enlace_drive', models.TextField()),
                ('Estado', models.TextField()),
            ],
        ),
    ]
